[postgresDatabase]
host = "127.0.0.1"
port = "5432"
username = "admin"
password = "qwerty123"
database = "local_db"

[generator]
pathToGeneratedServer = "internal/generated/schema/server.go"
pathToHandlers = "internal/handler"
